/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package qa.qcri.rtsm.ui;

import java.util.ArrayList;
import java.util.List;

import qa.qcri.rtsm.analysis.imran.AnalysisDriver;
import qa.qcri.rtsm.analysis.imran.FacebookShareAnalysis;
import qa.qcri.rtsm.analysis.imran.TimeSeriesIntervals;
import qa.qcri.rtsm.analysis.imran.TimeSeriesSorted;
import qa.qcri.rtsm.analysis.imran.TweetsAnalysis;
import qa.qcri.rtsm.analysis.imran.VisitsAnalysis;
import qa.qcri.rtsm.util.ExportData;

/**
 *
 * @author Imran
 */
public class RTSMUI extends javax.swing.JFrame {

    ContextMenuMouseListener ccp_menu =null;
    
    VisitsAnalysis visitsAnalysis;
    TimeSeriesSorted v_ts;
    List<TimeSeriesSorted> sortedTSVisits;
    
    TweetsAnalysis tweetsAnalysis;
    TimeSeriesSorted twt_ts;
    
    FacebookShareAnalysis fbAnalysis;
    TimeSeriesSorted fb_ts;
    
    List<TimeSeriesSorted> acTSList = new ArrayList<TimeSeriesSorted>();
    /**
     * Creates new form RTSMUI
     */
    public RTSMUI() {
        initComponents();
        ccp_menu = new ContextMenuMouseListener();
        tweetsAnalysis = new TweetsAnalysis();
       // fbAnalysis = new FacebookShareAnalysis();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        VisitsPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lineChartbtn = new javax.swing.JButton();
        TSbtn = new javax.swing.JButton();
        v_ts_movAvg_btn = new javax.swing.JButton();
        movAvgPointsTxtB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        v_seriesType_dbox = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        keysTxtb = new javax.swing.JTextField();
        v_loadTS_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        visitTxtb = new javax.swing.JTextField();
        dataStatuslb = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        timeInterval_dbox = new javax.swing.JComboBox();
        all_keys_chk = new javax.swing.JCheckBox();
        specificKeytxtb = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        v_export_btn = new javax.swing.JButton();
        TweetsPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        twt_timeinterval_dbox = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        twt_key_txtb = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        twt_timeinterval_txtb = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        twt_export_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        twt_line_chart_btn = new javax.swing.JButton();
        twt_ts_chart_btn = new javax.swing.JButton();
        twt_mov_avg_chart_btn = new javax.swing.JButton();
        twt_movAvgPoints_TxtB = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        twt_seriesType_dbox = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        FBPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        fb_timeformat_dbox = new javax.swing.JComboBox();
        fb_absTS_btn = new javax.swing.JButton();
        fb_key_txtb = new javax.swing.JTextField();
        fb_relTS_btn = new javax.swing.JButton();
        fb_timeinterval_txtb = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fb_export_btn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        fb_timeInterval_dbox = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        fb_shares_lowerb_txtb = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        fb_line_chart_btn = new javax.swing.JButton();
        fb_ts_chart_btn = new javax.swing.JButton();
        fb_mov_avg_chart_btn = new javax.swing.JButton();
        fb_movAvgPoints_TxtB = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        fb_seriesType_dbox = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        mainAnalysis = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        ac_absTS_btn = new javax.swing.JButton();
        ac_key_txtb = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        ac_timeInterval_dbox = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        ac_shares_lowerb_txtb = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        ac_movAvgPoints_TxtB = new javax.swing.JTextField();
        ac_mov_avg_chart_btn = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Charts"));

        lineChartbtn.setText("Print Line Chart");
        lineChartbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineChartbtnActionPerformed(evt);
            }
        });

        TSbtn.setText("Print Time Series Chart");
        TSbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TSbtnActionPerformed(evt);
            }
        });

        v_ts_movAvg_btn.setText("Print Moving Avg Chart");
        v_ts_movAvg_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_ts_movAvg_btnActionPerformed(evt);
            }
        });

        movAvgPointsTxtB.setText("2");
        movAvgPointsTxtB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movAvgPointsTxtBActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel5.setText("Points to be used in Avg cal.");

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Series Type");

        v_seriesType_dbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RELATIVE", "ABSOLUTE", "NORMALIZED", " " }));
        v_seriesType_dbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_seriesType_dboxActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(v_ts_movAvg_btn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(movAvgPointsTxtB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(309, Short.MAX_VALUE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(lineChartbtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 153, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(TSbtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel21)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(v_seriesType_dbox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(15, 15, 15))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lineChartbtn)
                    .add(TSbtn))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(v_ts_movAvg_btn)
                    .add(movAvgPointsTxtB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(v_seriesType_dbox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel21))
                .add(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Loading"));

        jLabel1.setText("Number of articles to be fetched:");

        keysTxtb.setText("100");
        keysTxtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keysTxtbActionPerformed(evt);
            }
        });

        v_loadTS_btn.setText("Load Time Series Data");
        v_loadTS_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                v_loadTS_btnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                v_loadTS_btnMouseReleased(evt);
            }
        });
        v_loadTS_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_loadTS_btnActionPerformed(evt);
            }
        });

        jLabel2.setText("Minimum visit threshold:");

        visitTxtb.setText("0");
        visitTxtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitTxtbActionPerformed(evt);
            }
        });

        dataStatuslb.setForeground(new java.awt.Color(255, 0, 51));
        dataStatuslb.setText("NOT LOADED");

        jLabel4.setText("Data Status:");

        jLabel3.setText("Select the time interval:");

        timeInterval_dbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "v_1m", "v_10s", "v_1h" }));

        all_keys_chk.setText("All Keys");

        specificKeytxtb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                specificKeytxtbMouseClicked(evt);
            }
        });
        specificKeytxtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specificKeytxtbActionPerformed(evt);
            }
        });

        jLabel6.setText("Fetch specified article only:");

        v_export_btn.setForeground(new java.awt.Color(255, 102, 102));
        v_export_btn.setText("Export");
        v_export_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_export_btnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(v_loadTS_btn)
                        .add(63, 63, 63)
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(dataStatuslb)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(v_export_btn))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(visitTxtb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(timeInterval_dbox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(keysTxtb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(all_keys_chk))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel6)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(specificKeytxtb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 462, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(timeInterval_dbox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(keysTxtb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(all_keys_chk))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(specificKeytxtb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(visitTxtb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(v_loadTS_btn)
                    .add(jLabel4)
                    .add(dataStatuslb)
                    .add(v_export_btn))
                .add(30, 30, 30))
        );

        org.jdesktop.layout.GroupLayout VisitsPanelLayout = new org.jdesktop.layout.GroupLayout(VisitsPanel);
        VisitsPanel.setLayout(VisitsPanelLayout);
        VisitsPanelLayout.setHorizontalGroup(
            VisitsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(VisitsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(VisitsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        VisitsPanelLayout.setVerticalGroup(
            VisitsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(VisitsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 233, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Visits TimeSeries Analysis", VisitsPanel);
        VisitsPanel.getAccessibleContext().setAccessibleName("Settings");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Loading"));

        jLabel7.setText("Enter an article's URL");

        twt_timeinterval_dbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MIN", "HOURS", "DAYS", "MONTHS" }));
        twt_timeinterval_dbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twt_timeinterval_dboxActionPerformed(evt);
            }
        });

        jButton2.setText("Construct Absolute TimeSeries");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        twt_key_txtb.setText("http://www.aljazeera.com/indepth/opinion/2012/09/201291103825936625.html");
        twt_key_txtb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twt_key_txtbMouseClicked(evt);
            }
        });

        jButton3.setText("Construct Relative TimeSeries");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        twt_timeinterval_txtb.setText("1");
        twt_timeinterval_txtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twt_timeinterval_txtbActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Time Interval");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Time Format");

        twt_export_btn.setForeground(new java.awt.Color(255, 102, 102));
        twt_export_btn.setText("Export");
        twt_export_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twt_export_btnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jLabel7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(twt_key_txtb)
                        .addContainerGap())
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 225, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(57, 57, 57)
                        .add(jLabel8)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(twt_timeinterval_txtb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(53, 53, 53)
                        .add(jLabel9)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(twt_timeinterval_dbox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(twt_export_btn))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(twt_key_txtb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(26, 26, 26)
                .add(jButton2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton3)
                    .add(twt_timeinterval_dbox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(twt_timeinterval_txtb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8)
                    .add(jLabel9)
                    .add(twt_export_btn))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Charts"));

        twt_line_chart_btn.setText("Print Line Chart");
        twt_line_chart_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twt_line_chart_btnActionPerformed(evt);
            }
        });

        twt_ts_chart_btn.setText("Print Time Series Chart");
        twt_ts_chart_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twt_ts_chart_btnActionPerformed(evt);
            }
        });

        twt_mov_avg_chart_btn.setText("Print Moving Avg Chart");
        twt_mov_avg_chart_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twt_mov_avg_chart_btnActionPerformed(evt);
            }
        });

        twt_movAvgPoints_TxtB.setText("2");
        twt_movAvgPoints_TxtB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twt_movAvgPoints_TxtBActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel10.setText("Points to be used in Avg cal.");

        twt_seriesType_dbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RELATIVE", "ABSOLUTE", "NORMALIZED", " " }));
        twt_seriesType_dbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twt_seriesType_dboxActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Series Type");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(twt_mov_avg_chart_btn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel10)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(twt_movAvgPoints_TxtB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(311, Short.MAX_VALUE))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(twt_line_chart_btn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 153, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(twt_ts_chart_btn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel11)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(twt_seriesType_dbox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(twt_line_chart_btn)
                    .add(twt_ts_chart_btn))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(twt_mov_avg_chart_btn)
                    .add(twt_movAvgPoints_TxtB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(twt_seriesType_dbox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel11))
                .add(0, 0, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout TweetsPanelLayout = new org.jdesktop.layout.GroupLayout(TweetsPanel);
        TweetsPanel.setLayout(TweetsPanelLayout);
        TweetsPanelLayout.setHorizontalGroup(
            TweetsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(TweetsPanelLayout.createSequentialGroup()
                .add(18, 18, 18)
                .add(TweetsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        TweetsPanelLayout.setVerticalGroup(
            TweetsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(TweetsPanelLayout.createSequentialGroup()
                .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 158, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 115, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tweets TimeSeries Analysis", TweetsPanel);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Loading"));

        jLabel12.setText("Enter an article's URL");

        fb_timeformat_dbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MIN", "SECONDS", "HOURS", "DAYS", "MONTHS" }));
        fb_timeformat_dbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb_timeformat_dboxActionPerformed(evt);
            }
        });

        fb_absTS_btn.setText("Construct Absolute TimeSeries");
        fb_absTS_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb_absTS_btnActionPerformed(evt);
            }
        });

        fb_key_txtb.setText("http://www.aljazeera.com/news/middleeast/2012/09/2012914162952845789.html");
        fb_key_txtb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fb_key_txtbMouseClicked(evt);
            }
        });
        fb_key_txtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb_key_txtbActionPerformed(evt);
            }
        });

        fb_relTS_btn.setText("Construct Relative TimeSeries");
        fb_relTS_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb_relTS_btnActionPerformed(evt);
            }
        });

        fb_timeinterval_txtb.setText("1");
        fb_timeinterval_txtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb_timeinterval_txtbActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel13.setText("Time Interval");

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel14.setText("Time Format");

        fb_export_btn.setForeground(new java.awt.Color(255, 102, 102));
        fb_export_btn.setText("Export");
        fb_export_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb_export_btnActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel17.setText("Select the time interval:");

        fb_timeInterval_dbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "f_s_1m", "f_s_10s", "f_s_1h" }));

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel18.setText("Minimum visit threshold:");

        fb_shares_lowerb_txtb.setText("0");
        fb_shares_lowerb_txtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb_shares_lowerb_txtbActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(jLabel12)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(fb_key_txtb, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel6Layout.createSequentialGroup()
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel6Layout.createSequentialGroup()
                                .add(fb_relTS_btn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 225, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jLabel13)
                                .add(12, 12, 12)
                                .add(fb_timeinterval_txtb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jLabel14)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(fb_timeformat_dbox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel6Layout.createSequentialGroup()
                                .add(fb_absTS_btn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 225, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jLabel17)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(fb_timeInterval_dbox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(jLabel18)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel6Layout.createSequentialGroup()
                                .add(0, 31, Short.MAX_VALUE)
                                .add(fb_export_btn))
                            .add(jPanel6Layout.createSequentialGroup()
                                .add(fb_shares_lowerb_txtb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12)
                    .add(fb_key_txtb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(21, 21, 21)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(fb_shares_lowerb_txtb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel18)
                    .add(fb_timeInterval_dbox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel17)
                    .add(fb_absTS_btn))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 23, Short.MAX_VALUE)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(fb_relTS_btn)
                    .add(fb_timeformat_dbox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(fb_timeinterval_txtb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel13)
                    .add(jLabel14)
                    .add(fb_export_btn))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Charts"));

        fb_line_chart_btn.setText("Print Line Chart");
        fb_line_chart_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb_line_chart_btnActionPerformed(evt);
            }
        });

        fb_ts_chart_btn.setText("Print Time Series Chart");
        fb_ts_chart_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb_ts_chart_btnActionPerformed(evt);
            }
        });

        fb_mov_avg_chart_btn.setText("Print Moving Avg Chart");
        fb_mov_avg_chart_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb_mov_avg_chart_btnActionPerformed(evt);
            }
        });

        fb_movAvgPoints_TxtB.setText("2");
        fb_movAvgPoints_TxtB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb_movAvgPoints_TxtBActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel15.setText("Points to be used in Avg cal.");

        fb_seriesType_dbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RELATIVE", "ABSOLUTE", "NORMALIZED", " " }));
        fb_seriesType_dbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb_seriesType_dboxActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel16.setText("Series Type");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(fb_mov_avg_chart_btn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel15)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(fb_movAvgPoints_TxtB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(317, Short.MAX_VALUE))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(fb_line_chart_btn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 153, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(fb_ts_chart_btn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel16)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(fb_seriesType_dbox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(fb_line_chart_btn)
                    .add(fb_ts_chart_btn))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel15)
                    .add(fb_mov_avg_chart_btn)
                    .add(fb_movAvgPoints_TxtB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(fb_seriesType_dbox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel16))
                .add(0, 0, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout FBPanelLayout = new org.jdesktop.layout.GroupLayout(FBPanel);
        FBPanel.setLayout(FBPanelLayout);
        FBPanelLayout.setHorizontalGroup(
            FBPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(FBPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(FBPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(FBPanelLayout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(FBPanelLayout.createSequentialGroup()
                        .add(jPanel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(18, 18, 18))))
        );
        FBPanelLayout.setVerticalGroup(
            FBPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(FBPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Facebook Shares Analysis", FBPanel);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Loading"));

        jLabel19.setText("Enter an article's URL");

        ac_absTS_btn.setText("Construct TimeSeries");
        ac_absTS_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac_absTS_btnActionPerformed(evt);
            }
        });

        ac_key_txtb.setText("http://www.aljazeera.com/news/middleeast/2012/09/2012914162952845789.html");
        ac_key_txtb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ac_key_txtbMouseClicked(evt);
            }
        });
        ac_key_txtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac_key_txtbActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel22.setText("Select the time interval:");

        ac_timeInterval_dbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1m", "10s", "1h" }));

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel23.setText("Minimum visit threshold:");

        ac_shares_lowerb_txtb.setText("0");
        ac_shares_lowerb_txtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac_shares_lowerb_txtbActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel20.setText("Points to be used in Avg cal.");

        ac_movAvgPoints_TxtB.setText("2");
        ac_movAvgPoints_TxtB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac_movAvgPoints_TxtBActionPerformed(evt);
            }
        });

        ac_mov_avg_chart_btn.setText("Print Moving Avg Chart");
        ac_mov_avg_chart_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac_mov_avg_chart_btnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel7Layout = new org.jdesktop.layout.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel7Layout.createSequentialGroup()
                        .add(jLabel19)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(ac_key_txtb, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE))
                    .add(jPanel7Layout.createSequentialGroup()
                        .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(ac_absTS_btn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 192, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(ac_mov_avg_chart_btn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(37, 37, 37)
                        .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel7Layout.createSequentialGroup()
                                .add(jLabel20)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(ac_movAvgPoints_TxtB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel7Layout.createSequentialGroup()
                                .add(jLabel22)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(ac_timeInterval_dbox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(44, 44, 44)
                                .add(jLabel23)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(ac_shares_lowerb_txtb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel19)
                    .add(ac_key_txtb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(21, 21, 21)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(ac_shares_lowerb_txtb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel23)
                    .add(ac_timeInterval_dbox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel22)
                    .add(ac_absTS_btn))
                .add(18, 18, 18)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel20)
                    .add(ac_movAvgPoints_TxtB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ac_mov_avg_chart_btn))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout mainAnalysisLayout = new org.jdesktop.layout.GroupLayout(mainAnalysis);
        mainAnalysis.setLayout(mainAnalysisLayout);
        mainAnalysisLayout.setHorizontalGroup(
            mainAnalysisLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainAnalysisLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(18, 18, 18))
        );
        mainAnalysisLayout.setVerticalGroup(
            mainAnalysisLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainAnalysisLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 166, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Accumulative Analysis", mainAnalysis);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 793, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 462, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void keysTxtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keysTxtbActionPerformed
    }//GEN-LAST:event_keysTxtbActionPerformed

    private void v_loadTS_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_loadTS_btnActionPerformed

        
        Integer keysRange = Integer.parseInt(keysTxtb.getText());
        Integer visitLimit = Integer.parseInt(visitTxtb.getText());
        visitsAnalysis = new VisitsAnalysis();
        visitsAnalysis.getTimeSeriesKeyspace();
        sortedTSVisits = new ArrayList<TimeSeriesSorted>();
        List<String> keysList;
        String specifiedKey = specificKeytxtb.getText().trim();
        if (specifiedKey.isEmpty()) {
            if (all_keys_chk.isSelected()) {
                keysList = visitsAnalysis.getTimeSeriesKeyspace().getAllArticles(StaticVars.ALJAZEERA_DOMAIN);
            } else {
                keysList = visitsAnalysis.getTimeSeriesKeyspace().getNKeys(keysRange, StaticVars.ALJAZEERA_DOMAIN);
            }
        } else {
            visitsAnalysis.getTimeSeriesKeyspace();
            keysList = new ArrayList<String>();
            keysList.add(specifiedKey);
        }
        
        for (String key: keysList){
            v_ts = new TimeSeriesSorted();
            v_ts = visitsAnalysis.getTimeSeriesColumnValues(key, timeInterval_dbox.getSelectedItem().toString(), visitLimit);
            sortedTSVisits.add(v_ts);
        }
        
        dataStatuslb.setText("LOADED");
    }//GEN-LAST:event_v_loadTS_btnActionPerformed

    private void visitTxtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitTxtbActionPerformed
    }//GEN-LAST:event_visitTxtbActionPerformed

    private void lineChartbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineChartbtnActionPerformed
        visitsAnalysis.drawLineChart(sortedTSVisits);
    }//GEN-LAST:event_lineChartbtnActionPerformed

    private void TSbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TSbtnActionPerformed
        visitsAnalysis.drawTSChart(sortedTSVisits, "R", true);
    }//GEN-LAST:event_TSbtnActionPerformed

    private void v_loadTS_btnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v_loadTS_btnMouseReleased
    }//GEN-LAST:event_v_loadTS_btnMouseReleased

    private void v_loadTS_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v_loadTS_btnMousePressed
        dataStatuslb.setText("LOADING...");
    }//GEN-LAST:event_v_loadTS_btnMousePressed

    private void v_ts_movAvg_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_ts_movAvg_btnActionPerformed
        List<TimeSeriesSorted> v_ts_list = new ArrayList<TimeSeriesSorted>();
        int c=0;
        for (TimeSeriesSorted series: sortedTSVisits){
            
            System.out.println(c++);
            series.setChartSeries(v_seriesType_dbox.getSelectedItem().toString());
            v_ts_list.add(series);
        }
        Integer avgCalPoints = Integer.parseInt(movAvgPointsTxtB.getText().toString());
        visitsAnalysis.drawMovAvgChart(v_ts_list, avgCalPoints, true);
    }//GEN-LAST:event_v_ts_movAvg_btnActionPerformed

    private void movAvgPointsTxtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movAvgPointsTxtBActionPerformed
    }//GEN-LAST:event_movAvgPointsTxtBActionPerformed

    private void specificKeytxtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specificKeytxtbActionPerformed

    }//GEN-LAST:event_specificKeytxtbActionPerformed

    private void specificKeytxtbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_specificKeytxtbMouseClicked
        ccp_menu.mouseClicked(evt);
    }//GEN-LAST:event_specificKeytxtbMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String key = twt_key_txtb.getText().trim();
        if (tweetsAnalysis.getTweetsKeyspace() == null)
        tweetsAnalysis.getTweetsKeyspace();
        twt_ts = tweetsAnalysis.constructAccumulativeTweetsTS(key);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void twt_timeinterval_dboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twt_timeinterval_dboxActionPerformed
    }//GEN-LAST:event_twt_timeinterval_dboxActionPerformed

    private void twt_timeinterval_txtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twt_timeinterval_txtbActionPerformed
    }//GEN-LAST:event_twt_timeinterval_txtbActionPerformed

    private void twt_line_chart_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twt_line_chart_btnActionPerformed
    }//GEN-LAST:event_twt_line_chart_btnActionPerformed

    private void twt_ts_chart_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twt_ts_chart_btnActionPerformed
        twt_ts.setChartSeries(twt_seriesType_dbox.getSelectedItem().toString());
        String seriesType = twt_seriesType_dbox.getSelectedItem().toString();
        twt_ts.setAlias("Tweets");
        List<TimeSeriesSorted> tsList = new ArrayList<TimeSeriesSorted>();
        tsList.add(twt_ts);
        tweetsAnalysis.drawTSChart(tsList, seriesType);
    }//GEN-LAST:event_twt_ts_chart_btnActionPerformed

    private void twt_mov_avg_chart_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twt_mov_avg_chart_btnActionPerformed
        twt_ts.setChartSeries(twt_seriesType_dbox.getSelectedItem().toString());
        int point = Integer.parseInt(twt_movAvgPoints_TxtB.getText().trim());
        twt_ts.setAlias("Tweets");
        List<TimeSeriesSorted> tsList = new ArrayList<TimeSeriesSorted>();
        tsList.add(twt_ts);
        tweetsAnalysis.drawMovAvgChart(tsList, point, true);
        
    }//GEN-LAST:event_twt_mov_avg_chart_btnActionPerformed

    private void twt_movAvgPoints_TxtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twt_movAvgPoints_TxtBActionPerformed
    }//GEN-LAST:event_twt_movAvgPoints_TxtBActionPerformed

    private void twt_key_txtbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twt_key_txtbMouseClicked
        ccp_menu.mouseClicked(evt);
    }//GEN-LAST:event_twt_key_txtbMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int timeInterval = Integer.parseInt(twt_timeinterval_txtb.getText().trim());
        String timeFormat = twt_timeinterval_dbox.getSelectedItem().toString();
       
        if (tweetsAnalysis.getTweetsKeyspace() == null)
        tweetsAnalysis.getTweetsKeyspace();
        twt_ts = tweetsAnalysis.constructRelativeSeries(twt_ts, timeInterval, timeFormat);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void twt_seriesType_dboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twt_seriesType_dboxActionPerformed
    }//GEN-LAST:event_twt_seriesType_dboxActionPerformed

    private void fb_timeformat_dboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb_timeformat_dboxActionPerformed
    }//GEN-LAST:event_fb_timeformat_dboxActionPerformed

    private void fb_absTS_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb_absTS_btnActionPerformed
        fbAnalysis = new FacebookShareAnalysis();
         fbAnalysis.getTimeSeriesKeyspace();
         
        String key = fb_key_txtb.getText().trim();
        String timeInterval = fb_timeInterval_dbox.getSelectedItem().toString();
        int lowerBound = Integer.parseInt(fb_shares_lowerb_txtb.getText().trim());
        fb_ts = fbAnalysis.getTimeSeriesColumnValues(key, timeInterval, lowerBound);
        
    }//GEN-LAST:event_fb_absTS_btnActionPerformed

    private void fb_key_txtbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fb_key_txtbMouseClicked
        ccp_menu.mouseClicked(evt);
    }//GEN-LAST:event_fb_key_txtbMouseClicked

    private void fb_relTS_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb_relTS_btnActionPerformed
        int timeInterval = Integer.parseInt(fb_timeinterval_txtb.getText().trim());
            fbAnalysis.getTimeSeriesKeyspace();
        fb_ts = fbAnalysis.constructRelativeSeries2(fb_ts, timeInterval, fb_timeformat_dbox.getSelectedItem().toString());
    }//GEN-LAST:event_fb_relTS_btnActionPerformed

    private void fb_timeinterval_txtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb_timeinterval_txtbActionPerformed
    }//GEN-LAST:event_fb_timeinterval_txtbActionPerformed

    private void fb_line_chart_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb_line_chart_btnActionPerformed
    }//GEN-LAST:event_fb_line_chart_btnActionPerformed

    private void fb_ts_chart_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb_ts_chart_btnActionPerformed
        fb_ts.setChartSeries(fb_seriesType_dbox.getSelectedItem().toString());
        List<TimeSeriesSorted> tsList = new ArrayList<TimeSeriesSorted>();
        tsList.add(fb_ts);
        fbAnalysis.drawTSChart(tsList, fb_seriesType_dbox.getSelectedItem().toString());
    }//GEN-LAST:event_fb_ts_chart_btnActionPerformed

    private void fb_mov_avg_chart_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb_mov_avg_chart_btnActionPerformed
        List<TimeSeriesSorted> tsList = new ArrayList<TimeSeriesSorted>();
        fb_ts.setChartSeries(fb_seriesType_dbox.getSelectedItem().toString());
        tsList.add(fb_ts);
        int points = Integer.parseInt(fb_movAvgPoints_TxtB.getText().trim());
        
        fbAnalysis.drawMovAvgChart(tsList, points, true);
    }//GEN-LAST:event_fb_mov_avg_chart_btnActionPerformed

    private void fb_movAvgPoints_TxtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb_movAvgPoints_TxtBActionPerformed
    }//GEN-LAST:event_fb_movAvgPoints_TxtBActionPerformed

    private void fb_seriesType_dboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb_seriesType_dboxActionPerformed
    }//GEN-LAST:event_fb_seriesType_dboxActionPerformed

    private void fb_shares_lowerb_txtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb_shares_lowerb_txtbActionPerformed
    }//GEN-LAST:event_fb_shares_lowerb_txtbActionPerformed

    private void fb_key_txtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb_key_txtbActionPerformed
    }//GEN-LAST:event_fb_key_txtbActionPerformed

    private void ac_absTS_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac_absTS_btnActionPerformed
        visitsAnalysis = new VisitsAnalysis();
        visitsAnalysis.getTimeSeriesKeyspace();
        tweetsAnalysis = new TweetsAnalysis();
        tweetsAnalysis.getTweetsKeyspace();
        fbAnalysis = new FacebookShareAnalysis();
        fbAnalysis.getTimeSeriesKeyspace();
        acTSList.clear();
        
        String key= ac_key_txtb.getText().trim();
        
        int lower_bound = Integer.parseInt(ac_shares_lowerb_txtb.getText().trim());
        TimeSeriesSorted visitTS = visitsAnalysis.getTimeSeriesColumnValues(key, TimeSeriesIntervals.KEY_ONE_MINUTE, lower_bound);
        visitTS = visitsAnalysis.getAveNormalizedSeries(visitTS);
        visitTS.setAlias("Visits");
        visitTS.setChartSeries(StaticVars.SERIES_TYPE_NORMALIZED);
        
        TimeSeriesSorted FBTS = fbAnalysis.getTimeSeriesColumnValues(key, TimeSeriesIntervals.KEY_ONE_MINUTE_FB, lower_bound);
        FBTS = fbAnalysis.constructRelativeSeries2(FBTS, 1, StaticVars.TIME_FORMAT_MIN);
        FBTS.setAlias("FacebookShares");
        FBTS.setChartSeries(StaticVars.SERIES_TYPE_RELATIVE);

        TimeSeriesSorted tweetsTS = tweetsAnalysis.constructAccumulativeTweetsTS(key);
        tweetsTS = tweetsAnalysis.constructRelativeSeries(tweetsTS, 1, StaticVars.TIME_FORMAT_MIN);
        tweetsTS.setAlias("Tweets");
        tweetsTS.setChartSeries(StaticVars.SERIES_TYPE_RELATIVE);
        
        acTSList.add(visitTS);
        acTSList.add(FBTS);
        acTSList.add(tweetsTS);
        
    }//GEN-LAST:event_ac_absTS_btnActionPerformed

    private void ac_key_txtbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ac_key_txtbMouseClicked
        ccp_menu.mouseClicked(evt);
    }//GEN-LAST:event_ac_key_txtbMouseClicked

    private void ac_key_txtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac_key_txtbActionPerformed
    }//GEN-LAST:event_ac_key_txtbActionPerformed

    private void ac_shares_lowerb_txtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac_shares_lowerb_txtbActionPerformed
    }//GEN-LAST:event_ac_shares_lowerb_txtbActionPerformed

    private void ac_movAvgPoints_TxtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac_movAvgPoints_TxtBActionPerformed
    }//GEN-LAST:event_ac_movAvgPoints_TxtBActionPerformed

    private void ac_mov_avg_chart_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac_mov_avg_chart_btnActionPerformed
        AnalysisDriver analysis= new AnalysisDriver();
        int mov_avg_points = Integer.parseInt(ac_movAvgPoints_TxtB.getText().trim());
        analysis.drawMovAvgChart(acTSList, mov_avg_points, true);
    }//GEN-LAST:event_ac_mov_avg_chart_btnActionPerformed

    private void v_seriesType_dboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_seriesType_dboxActionPerformed
    }//GEN-LAST:event_v_seriesType_dboxActionPerformed

    private void twt_export_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twt_export_btnActionPerformed
        ExportData export = new ExportData();
        export.exportToCSV(twt_ts, "Tweets");
    }//GEN-LAST:event_twt_export_btnActionPerformed

    private void fb_export_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb_export_btnActionPerformed
        ExportData export = new ExportData();
        export.exportToCSV(fb_ts, "Facebook");
    }//GEN-LAST:event_fb_export_btnActionPerformed

    private void v_export_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_export_btnActionPerformed
        ExportData export = new ExportData();
        export.exportToCSV(v_ts, "Visits");
    }//GEN-LAST:event_v_export_btnActionPerformed
    

  
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {




        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RTSMUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RTSMUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RTSMUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RTSMUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new RTSMUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FBPanel;
    private javax.swing.JButton TSbtn;
    private javax.swing.JPanel TweetsPanel;
    private javax.swing.JPanel VisitsPanel;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton ac_absTS_btn;
    private javax.swing.JTextField ac_key_txtb;
    private javax.swing.JTextField ac_movAvgPoints_TxtB;
    private javax.swing.JButton ac_mov_avg_chart_btn;
    private javax.swing.JTextField ac_shares_lowerb_txtb;
    private javax.swing.JComboBox ac_timeInterval_dbox;
    private javax.swing.JCheckBox all_keys_chk;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JLabel dataStatuslb;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JButton fb_absTS_btn;
    private javax.swing.JButton fb_export_btn;
    private javax.swing.JTextField fb_key_txtb;
    private javax.swing.JButton fb_line_chart_btn;
    private javax.swing.JTextField fb_movAvgPoints_TxtB;
    private javax.swing.JButton fb_mov_avg_chart_btn;
    private javax.swing.JButton fb_relTS_btn;
    private javax.swing.JComboBox fb_seriesType_dbox;
    private javax.swing.JTextField fb_shares_lowerb_txtb;
    private javax.swing.JComboBox fb_timeInterval_dbox;
    private javax.swing.JComboBox fb_timeformat_dbox;
    private javax.swing.JTextField fb_timeinterval_txtb;
    private javax.swing.JButton fb_ts_chart_btn;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField keysTxtb;
    private javax.swing.JButton lineChartbtn;
    private javax.swing.JPanel mainAnalysis;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField movAvgPointsTxtB;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JTextField specificKeytxtb;
    private javax.swing.JComboBox timeInterval_dbox;
    private javax.swing.JButton twt_export_btn;
    private javax.swing.JTextField twt_key_txtb;
    private javax.swing.JButton twt_line_chart_btn;
    private javax.swing.JTextField twt_movAvgPoints_TxtB;
    private javax.swing.JButton twt_mov_avg_chart_btn;
    private javax.swing.JComboBox twt_seriesType_dbox;
    private javax.swing.JComboBox twt_timeinterval_dbox;
    private javax.swing.JTextField twt_timeinterval_txtb;
    private javax.swing.JButton twt_ts_chart_btn;
    private javax.swing.JButton v_export_btn;
    private javax.swing.JButton v_loadTS_btn;
    private javax.swing.JComboBox v_seriesType_dbox;
    private javax.swing.JButton v_ts_movAvg_btn;
    private javax.swing.JTextField visitTxtb;
    // End of variables declaration//GEN-END:variables
}
